# script generated by Insure++
# Run "-Zoicompiler /usr/bin/g++" -Wall -g -I. -I./exttypes -c exttypes/mvectors.cpp -o exttypes/mvectors.o
proc GetExtraMpfArgs { args } {
    if { $args == {exttypes/mvectors.cpp} } { 
        return { -si {initfuncname _insight_I6_1_gpp_mvectorsWc87161078394713} }
    } else {
         return {};
    }
}
