# script generated by Insure++
# Run "-Zoicompiler /usr/bin/g++" -Wall -g -I. -I./exttypes -c exttypes/dct.cpp -o exttypes/dct.o
proc GetExtraMpfArgs { args } {
    if { $args == {exttypes/dct.cpp} } { 
        return { -si {initfuncname _insight_I6_1_gpp_dct86981078394711} }
    } else {
         return {};
    }
}
