#ifndef OPTICALFLOWCV_GLOBAL_H
#define OPTICALFLOWCV_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPTICALFLOWCV_LIBRARY)
#  define OPTICALFLOWCVSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPTICALFLOWCVSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPTICALFLOWCV_GLOBAL_H
