# script generated by Insure++
# Run "-Zoicompiler /usr/bin/g++" -Wall -g -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/include -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/inc -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/mat_sym -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/cprim -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/pyramide -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/memoire -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/compense -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/contrib/localpng -I/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/contrib/mpeg2dec -c /udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/cprim/damem.c -o /udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/cprim/damem.o
proc GetExtraMpfArgs { args } {
    if { $args == {/udd/fspindle/soft/Equipe/motion-2D/Motion2D-1.3.11/src/cprim/damem.c} } { 
        return { -si {initfuncname _insight_I6_1_gpp_damem80431078394615} }
    } else {
         return {};
    }
}
