# script generated by Insure++
# Run "-Zoicompiler /usr/bin/g++" -Wall -g -I. -I./exttypes -c display.cpp -o display.o
proc GetExtraMpfArgs { args } {
    if { $args == {display.cpp} } { 
        return { -si {initfuncname _insight_I6_1_gpp_displayWcp85981078394698} }
    } else {
         return {};
    }
}
