# script generated by Insure++
# Run "-Zoicompiler /usr/bin/g++" -Wall -g -I. -I./exttypes -c idctref.cpp -o idctref.o
proc GetExtraMpfArgs { args } {
    if { $args == {idctref.cpp} } { 
        return { -si {initfuncname _insight_I6_1_gpp_idctrefWcp85801078394696} }
    } else {
         return {};
    }
}
