# script generated by Insure++
# Run "-Zoicompiler /usr/bin/g++" -Wall -g -I. -I./exttypes -c idct.cpp -o idct.o
proc GetExtraMpfArgs { args } {
    if { $args == {idct.cpp} } { 
        return { -si {initfuncname _insight_I6_1_gpp_idct85621078394695} }
    } else {
         return {};
    }
}
