# script generated by Insure++
# Run "-Zoicompiler /usr/bin/g++" -Wall -g -I. -I./exttypes -c verify.cpp -o verify.o
proc GetExtraMpfArgs { args } {
    if { $args == {verify.cpp} } { 
        return { -si {initfuncname _insight_I6_1_gpp_verify86481078394703} }
    } else {
         return {};
    }
}
